---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This protocol is for Oxford Nanopore sequencing of plasmid or bacterial genome samples using rapid barcoding kits (SQK-RBK...).  

**1. Tagmentation**  

 - adjust DNA with water, add barcodes (Opentrons)

| |gDNA| plasmid |
|:---|---:|---:|
| DNA + water | 9.0 ul | 4.5 ul |
| rapid barcode | 1.0 ul | 0.5 ul|
| **total** | **10.0 ul** | **5.0 ul** |


 - incubate 30 degrees for 2 minutes
 - incubate 80 degress for 2 minutes

*** 
 
**2. Pool and purify**  

 - pool all samples (Opentrons)  
 - add equal volume SPRI beads, incubate 5 min room temperature  
 - wash beads 2x with 80% EtOH  
 - aspirate all EtOH and dry beads 30 seconds  
 - resuspend in 15 ul EB, incubate 10 minutes, take out eluate in new tube (increase the elution volume by 15ul for each 12 plasmids in the pool)  
 
***

**3. RAP addition**  

 - measure pool conc with Qbit  
 - use 50 fmol in 5 ul (Flongle) or 100 fmol in 11 ul (MinION)
 - add RAP-F 0.5 ul (Flongle) or 1 ul (MinION)
 - incubate 5 min RT
 - put on ice

***

**4. Load flow cell**  

 - prime flow cell 3 ul FLT to 117 ul FB (Flongle) or 30 ul FLT to one vial of FB (MinION)
 - library mix
 
|    | Flongle | MinION |
|:---|---:|---:|
| SBII | 15 ul | 37.5 ul |
| LBII | 10 ul | 25.5 ul|
| library | 5 ul | 12.0 ul|


Load 2 or more times if needed and enough library is present

***

**5. Data analysis**   

Use high accuracy basecallig and demultiplexing in MinKNOW. Recommended pipelines:   
<a href="https://github.com/epi2me-labs/wf-clone-validation" target="_blank">plasmid de novo assembly pipeline</a>   
<a href="https://github.com/epi2me-labs/wf-bacterial-genomes" target="_blank">bacterial genomes pipeline</a>



